const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/server-test.cjs','utf8').split("test('B2 normal set")[0];
const tests=`
vm.runInContext(fs.readFileSync(__dirname+'/Backup.gs','utf8'),ctx);
const exported=s=>Object.fromEntries(Object.entries(s.tables).map(([k,v])=>[k,[...v.values()]]));
const metadata=s=>({environment:s.config.environment,start_revision:ctx.hubSetting_(s,'next_change'),end_revision:ctx.hubSetting_(s,'next_change'),start_generation:1,end_generation:1,now});
function example(){const s=fresh(),op=meal();app(s,op);intake(s,set(),2);intake(s,['note','補足','筋トレ','2026-10-01','Pull','ダンベルカール','','分類=身体状態; 発言者=本人','架空メモ'],3);return s;}
test('split snapshot restores all IDs, typed null/zero, receipts and aggregates in a separate store',()=>{const s=example(),before=copy(exported(s)),b=ctx.hubBackupCreate_(before,metadata(s),1000);assert.ok(b.manifest.tables.some(t=>t.parts.length>1));const plan=ctx.hubBackupRestorePlan_(b.manifest,b.objects,now+1),target=new MemoryStore();for(const [t,rows] of Object.entries(plan.tables))for(const row of rows)target.seed(t,row);assert.equal(ctx.hubSetting_(target,'generation'),2);for(const t of Object.keys(schema.tables))assert.deepEqual([...target.tables[t].keys()],[...s.tables[t].keys()]);assert.deepEqual(copy(target.tables.DailySummary.get('2026-10-01')),copy(s.tables.DailySummary.get('2026-10-01')));assert.equal([...target.tables.IntakeNutrients.values()].find(n=>n.nutrient_id==='fat_g').value,0);assert.equal([...target.tables.IntakeNutrients.values()].find(n=>n.nutrient_id==='carbohydrate_g').value,null);assert.deepEqual(copy(exported(s)),before);});
test('source mutations during capture reject the snapshot',()=>{const s=example();assert.throws(()=>ctx.hubBackupCreate_(exported(s),{...metadata(s),end_revision:999}),/BACKUP_CHANGED/);assert.throws(()=>ctx.hubBackupCreate_(exported(s),{...metadata(s),end_generation:2}),/BACKUP_CHANGED/);});
test('tampered/missing objects, unfinished manifest and altered manifest are rejected',()=>{const s=example(),b=ctx.hubBackupCreate_(exported(s),metadata(s));const hash=Object.keys(b.objects)[0];assert.throws(()=>ctx.hubBackupVerify_(b.manifest,{...b.objects,[hash]:'corrupt'}),/BACKUP_PART_HASH/);const o={...b.objects};delete o[hash];assert.throws(()=>ctx.hubBackupVerify_(b.manifest,o),/BACKUP_PART_HASH/);assert.throws(()=>ctx.hubBackupVerify_({...b.manifest,complete:false},b.objects),/BACKUP_INCOMPLETE/);assert.throws(()=>ctx.hubBackupVerify_({...b.manifest,generation:2},b.objects),/BACKUP_MANIFEST_HASH/);});
test('wrong numeric types, duplicate IDs and dangling parents reject even a rehashed snapshot',()=>{const s=example(),base=exported(s);let a=copy(base);a.TrainingSets[0].reps='8';assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/COLUMN_TYPE/);a=copy(base);a.Meals.push(a.Meals[0]);assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/BACKUP_DUPLICATE/);a=copy(base);a.MealItems[0].meal_id=crypto.randomUUID();assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/BACKUP_INDEX_REFERENCE|BACKUP_ORPHAN/);});
test('missing nutrients, aggregate mismatches and sync gaps cannot restore',()=>{const s=example(),base=exported(s);let a=copy(base);a.IntakeNutrients.pop();assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/BACKUP_INDEX/);a=copy(base);a.DailySummary[0].kcal++;assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/BACKUP_SUMMARY/);a=copy(base);a.SyncChanges.pop();assert.throws(()=>ctx.hubBackupCreate_(a,metadata(s)),/BACKUP_CHANGE_GAP/);});
test('removed rows remain tombstones and source real-data gates are enforced',()=>{const s=fresh(),op=meal();app(s,op);app(s,meal('remove_meal',op.entity_id,1,null));const b=ctx.hubBackupCreate_(exported(s),metadata(s));assert.equal(ctx.hubBackupVerify_(b.manifest,b.objects).Meals[0].status,'removed');ctx.hubSet_(s,'real_data_enabled',true,now);s.commit();assert.throws(()=>ctx.hubBackupCreate_(exported(s),metadata(s)),/REAL_DATA_SETTING_MISMATCH/);});
test('daily7 weekly4 monthly12 retain at most23 complete snapshots and protect shared and unfinished references',()=>{const s=fresh(),base=ctx.hubBackupCreate_(exported(s),metadata(s));const manifests=[];for(let i=0;i<500;i++){const m=copy(base.manifest);m.id='test-'+i;m.created_at=new Date(now-i*86400000).toISOString();manifests.push(m);}const unfinished={...copy(base.manifest),id:'draft',complete:false,tables:[{parts:[{sha256:'unfinished-object'}]}]};manifests.push(unfinished);const r=ctx.hubBackupRetention_(manifests);assert.ok(r.keep.length<=23);assert.equal(r.keep.length,new Set(r.keep).size);assert.ok(r.keep.includes('test-0'));assert.ok(r.retire.length>450);for(const h of Object.keys(base.objects))assert.ok(r.protected_objects.includes(h));assert.ok(r.protected_objects.includes('unfinished-object'));assert.ok(!r.retire.includes('draft'));});
console.log('Hub backup: '+passed+' PASSED');
`;
vm.runInNewContext(source+tests,{require,console,Buffer,__dirname});
