const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const ctx={console,ensure_:(v,e)=>{if(!v)throw Error(e);},hubIsId_:v=>/^[0-9a-f-]{36}$/.test(v),hubHash_:v=>crypto.createHash('sha256').update(v).digest('hex')};
const principal=email=>({getEmail:()=>email}),iter=items=>{let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};};
const c={environment:'PHH_TEST',owner:'s@example.test',chat:'c@example.test',canonical:'canonical',inbox:'inbox',results:'results',real_data_enabled:false};
const made=Date.parse('2026-10-01T00:00:00Z'),due=made+7*86400000;
let effects=[],failTrash=false,files=new Map();
class File {
 constructor(id,name,body){this.id=id;this.name=name;this.body=body;this.owner=c.owner;this.viewers=[c.chat];this.editors=[];this.access='private';this.parents=['root'];this.trash=false;}
 getId(){return this.id;}getName(){return this.name;}getOwner(){return principal(this.owner);}getSharingAccess(){return this.access;}getEditors(){return this.editors.map(principal);}getViewers(){return this.viewers.map(principal);}getParents(){return iter(this.parents.map(id=>({getId:()=>id})));}getSize(){return Buffer.byteLength(this.body);}getBlob(){return {getDataAsString:()=>this.body};}removeViewer(email){effects.push('revoke:'+this.id);this.viewers=this.viewers.filter(v=>v!==email);}isTrashed(){return this.trash;}setTrashed(v){effects.push('trash:'+this.id);if(failTrash)throw Error('Drive failure');this.trash=v;}
}
const root=new File('root','root','');root.viewers=[];
ctx.DriveApp={Access:{PRIVATE:'private'},getFileById:id=>files.get(id)};
ctx.hubBackupPrivate_=(f,owner)=>{ctx.ensure_(f.getOwner().getEmail()===owner && f.getSharingAccess()==='private' && f.getEditors().length===0 && f.getViewers().length===0,'BACKUP_ACL');};
vm.runInNewContext(fs.readFileSync(__dirname+'/Expiry.gs','utf8'),ctx);
function fixture(){effects=[];files=new Map();const m={schema_version:1,environment:c.environment,request_id:'11111111-1111-4111-a111-111111111111',generation:'22222222-2222-4222-a222-222222222222',last_generated_at:new Date(made).toISOString(),expires_at:new Date(due).toISOString(),pages:[]};for(let i=0;i<2;i++){const name='PHH_QUERY_'+c.environment+'_'+m.request_id+'_'+m.generation+'_p'+i+'.txt',body='架空のページ '+i,f=new File('file'+i,name,body);files.set(f.id,f);m.pages.push({id:f.id,index:i,name,bytes:Buffer.byteLength(body),sha256:ctx.hubHash_(body)});}return m;}
let passed=0;function test(name,body){body();passed++;console.log('ok '+name);}
test('exact seventh day expires, earlier run and preview make no changes',()=>{const m=fixture();assert.equal(ctx.hubExpireDerivedPages_(m,c,root,due-1).expired,false);assert.equal(ctx.hubExpireDerivedPages_(m,c,root,due,true).preview,true);assert.deepEqual(effects,[]);assert.equal(ctx.hubExpireDerivedPages_(m,c,root,due).status,'expired');assert.deepEqual(effects,['revoke:file0','trash:file0','revoke:file1','trash:file1']);});
test('same IDs can resume after revoke succeeds but trash fails',()=>{const m=fixture();failTrash=true;assert.throws(()=>ctx.hubExpireDerivedPages_(m,c,root,due),/Drive failure/);failTrash=false;assert.equal(ctx.hubExpireDerivedPages_(m,c,root,due).status,'expired');effects=[];assert.equal(ctx.hubExpireDerivedPages_(m,c,root,due).status,'expired');assert.deepEqual(effects,[]);});
test('foreign parent, hash, bytes, name or ACL in the last page prevents all revokes',()=>{for(const mutate of [f=>f.parents=['elsewhere'],f=>f.body+='bad',f=>f.name='unrelated',f=>f.owner='other',f=>f.editors=[c.chat],f=>f.viewers=['other'],f=>f.access='public']){const m=fixture();mutate(files.get('file1'));assert.throws(()=>ctx.hubExpireDerivedPages_(m,c,root,due),/EXPIRY_/);assert.deepEqual(effects,[]);}});
test('real data, source books, shared root and changed environment stop before writes',()=>{let m=fixture();assert.throws(()=>ctx.hubExpireDerivedPages_(m,{...c,environment:'PHH_PRODUCTION'},root,due),/EXPIRY_ENVIRONMENT/);m.pages[0].id=c.canonical;assert.throws(()=>ctx.hubExpireDerivedPages_(m,c,root,due),/EXPIRY_SOURCE/);root.viewers=[c.chat];assert.throws(()=>ctx.hubExpireDerivedPages_(fixture(),c,root,due),/BACKUP_ACL/);root.viewers=[];assert.deepEqual(effects,[]);});
test('invalid dates, wrong expiry, duplicate IDs, page indexes and oversized pages reject',()=>{for(const mutate of [m=>m.last_generated_at='bad',m=>m.expires_at=new Date(due+1).toISOString(),m=>m.pages[1].id=m.pages[0].id,m=>m.pages[1].index=0,m=>m.pages[0].bytes=50001]){const m=fixture();mutate(m);assert.throws(()=>ctx.hubExpireDerivedPages_(m,c,root,due),/EXPIRY_/);assert.deepEqual(effects,[]);}});
console.log('Hub expiry: '+passed+' PASSED');
// 実際のDrive同様、フォルダー一覧からゴミ箱入りのページが消えても再開できる。
ctx.stable_=v=>JSON.stringify(v);ctx.hubCell_=v=>({userEnteredValue:typeof v==='number'?{numberValue:v}:{stringValue:String(v)}});ctx.MimeType={PLAIN_TEXT:'text/plain'};ctx.Utilities={newBlob:s=>({getBytes:()=>Array.from(Buffer.from(s))})};
let outputRows=[],batchWrites=0,failOutput=false,corruptOutput=false,props=new Map();
const sheet={getSheetId:()=>17,getMaxRows:()=>100,getLastRow:()=>outputRows.length};ctx.SpreadsheetApp={openById:id=>{assert.equal(id,c.results);return {getSheetByName:()=>sheet,getId:()=>id};}};
ctx.PropertiesService={getScriptProperties:()=>({getProperty:k=>props.get(k)||'',setProperty:(k,v)=>props.set(k,v)})};
ctx.Sheets={Spreadsheets:{Values:{batchGet:(_,{ranges})=>({valueRanges:ranges.map(r=>{let rows;if(r.endsWith('A1:F1'))rows=outputRows.length?[outputRows[0]]:[];else if(r.endsWith('A2:B'))rows=outputRows.slice(1).map(v=>v.slice(0,2));else{const n=Number(r.match(/!A(\d+)/)[1]);rows=outputRows[n-1]?[outputRows[n-1].slice()]:[];if(corruptOutput && rows[0])rows[0][2]='bad';}return {values:rows};})})},batchUpdate:({requests})=>{if(failOutput)throw Error('publish failure');batchWrites++;for(const r of requests)if(r.updateCells){const row=r.updateCells;outputRows[row.start.rowIndex]=row.rows[0].values.map(v=>Object.values(v.userEnteredValue)[0]);}}}};
function jobFixture(){const m=fixture();outputRows=[];batchWrites=0;failOutput=false;corruptOutput=false;props.clear();const f=new File('job','PHH_QUERY_'+c.environment+'_'+m.request_id+'_'+m.generation,'');f.viewers=[];f.children=[...files.values()];f.getFiles=()=>iter(f.children.filter(x=>!x.trash));f.createFile=(name,body)=>{const x=new File('manifest',name,body);x.viewers=[];x.parents=['job'];x.setContent=v=>{x.body=v;};f.children.push(x);return x;};f.children.forEach(x=>x.parents=['job']);return {m,f};}
test('registration persists and reuses a private manifest, publishes only derived result rows',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);ctx.hubSaveDerivedJob_(m,c,f);assert.equal(f.children.length,3);assert.equal(ctx.hubCompleteDerivedJob_(f,c,made).status,'ready');assert.equal(outputRows[1][2],'ready');assert.equal(outputRows[1][4],2);assert.ok(outputRows[1][5].includes('/file0/view'));const n=batchWrites;ctx.hubCompleteDerivedJob_(f,c,made);assert.equal(batchWrites,n);assert.deepEqual(effects,[]);});
test('expired output removes URLs and same manifest survives trash-filtered folder lists',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);ctx.hubCompleteDerivedJob_(f,c,due);assert.equal(outputRows[1][2],'expired');assert.equal(outputRows[1][5],'');assert.equal(ctx.hubReadDerivedJob_(f,c).job.status,'expired');effects=[];const n=batchWrites;ctx.hubCompleteDerivedJob_(f,c,due+1);assert.deepEqual(effects,[]);assert.equal(batchWrites,n);});
test('publication failure after cleanup is repaired with the same IDs and no repeat revokes',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);failOutput=true;assert.throws(()=>ctx.hubCompleteDerivedJob_(f,c,due),/publish failure/);assert.equal(ctx.hubReadDerivedJob_(f,c).job.status,'expired');effects=[];failOutput=false;ctx.hubCompleteDerivedJob_(f,c,due+1);assert.equal(outputRows[1][2],'expired');assert.deepEqual(effects,[]);});
test('changed manifest, duplicate result key and unexpected folder files cannot be silently replaced',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);const changed=JSON.parse(JSON.stringify(m));changed.expires_at=new Date(due+1).toISOString();assert.throws(()=>ctx.hubSaveDerivedJob_(changed,c,f),/EXPIRY_TIME/);ctx.hubCompleteDerivedJob_(f,c,made);outputRows.push(outputRows[1].slice());assert.throws(()=>ctx.hubCompleteDerivedJob_(f,c,made),/EXPIRY_RESULT_INDEX/);f.children.push(new File('unrelated','private-original','x'));assert.throws(()=>ctx.hubReadDerivedJob_(f,c),/EXPIRY_JOB_FILES/);assert.deepEqual(effects,[]);});
test('fresh result readback rejects mismatched data and later run repairs it',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);corruptOutput=true;assert.throws(()=>ctx.hubCompleteDerivedJob_(f,c,made),/EXPIRY_RESULT_READBACK/);corruptOutput=false;ctx.hubCompleteDerivedJob_(f,c,made);assert.equal(outputRows[1][2],'ready');});
test('bounded cleanup rotates jobs, preview preserves cursor and incomplete jobs remain pending',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);f.parents=['root'];const incomplete=new File('unfinished','z-unfinished','');incomplete.viewers=[];incomplete.parents=['root'];incomplete.getFiles=()=>iter([]);root.getFolders=()=>iter([f,incomplete]);assert.equal(ctx.hubCleanupDerivedJobs_(c,root,due,true).expired,1);assert.equal(props.size,0);ctx.hubCleanupDerivedJobs_(c,root,due);assert.equal(ctx.hubCleanupDerivedJobs_(c,root,due).processed,1);assert.equal(f.children[2].getName(),'expiry-manifest.json');assert.equal(props.get('PHH_QUERY_CLEANUP_CURSOR'),'z-unfinished');assert.equal(ctx.hubCleanupDerivedJobs_(c,root,due).expired,1);});
console.log('Hub expiry total: '+passed+' PASSED');
test('cleanup entry checks account/books, skips unconfigured roots, and releases its separate lock on failure',()=>{const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);ctx.hubConfig_=()=>c;let checks=0,released=0;ctx.hubCheckACL_=()=>checks++;ctx.hubCheckBookEnvs_=()=>checks++;ctx.LockService={getUserLock:()=>({tryLock:()=>true,releaseLock:()=>released++})};assert.equal(ctx.runHubExpiryCleanup().configured,false);assert.equal(released,0);props.set('PHH_QUERY_ROOT_ID','root');ctx.DriveApp.getFolderById=id=>{assert.equal(id,'root');throw Error('offline');};assert.throws(()=>ctx.runHubExpiryCleanup(),/offline/);assert.equal(released,1);assert.equal(checks,4);ctx.LockService.getUserLock=()=>({tryLock:()=>false,releaseLock:()=>{throw Error('not acquired');}});assert.throws(()=>ctx.runHubExpiryCleanup(),/BUSY/);});
test('ready publication refuses unshared or trashed pages; duplicate folders cannot be skipped',()=>{for(const mutate of [f=>f.viewers=[],f=>f.trash=true]){const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);mutate(f.children[0]);assert.throws(()=>ctx.hubCompleteDerivedJob_(f,c,made),/EXPIRY_NOT_READABLE/);assert.equal(batchWrites,0);}const {m,f}=jobFixture();ctx.hubSaveDerivedJob_(m,c,f);root.getFolders=()=>iter([f,f]);assert.throws(()=>ctx.hubCleanupDerivedJobs_(c,root,due),/EXPIRY_JOB_INDEX/);assert.deepEqual(effects,[]);});
console.log('Hub expiry final: '+passed+' PASSED');
