const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/server-test.cjs','utf8').split("test('B2 normal set")[0],harness={exports:{}};
new Function('require','module','__dirname',source+'\nmodule.exports={ctx,schema,copy};')(require,harness,__dirname);
const {ctx,schema,copy}=harness.exports;
for(const file of ['TrainingP3.gs','FoodP4.gs'])vm.runInContext(fs.readFileSync(__dirname+'/'+file,'utf8'),ctx);
const p3=copy(ctx.hubP3Schema_(schema));let passed=0;function test(name,fn){fn();passed++;console.log('ok '+name)}
const id=n=>`00000000-0000-4000-a000-${String(n).padStart(12,'0')}`;
const item=(n,kcal)=>({id:id(n),name:'架空食品'+n,quantity:1,unit:'個',preparation:'加熱済み',source:'推定',confidence:'中',nutrients:{kcal,protein:10,fat:0,carbohydrate:15}});
const meal=()=>({id:id(1),revision:1,date:'2026-10-02',slot:'朝食',items:[item(10,100),item(11,null)],removed:false});
const operation=(m=meal(),n=100)=>({schema_version:1,environment:'PHH_PRODUCTION',operation_id:id(n),entity_id:m.id,expected_revision:m.revision-1,action:m.revision===1?'confirm_food_meal':m.removed?'remove_food_meal':'update_food_meal',approval_state:'confirmed',synthetic:true,payload:m});
const empty=()=>({environment:'PHH_PRODUCTION',records:[],operations:{}});
test('additive 18 to 23 tables and all prior columns retained',()=>{const target=ctx.hubP4Schema_(p3);assert.equal(Object.keys(target.tables).length,23);for(const [table,def] of Object.entries(p3.tables))assert.deepEqual(copy(target.tables[table].columns.slice(0,def.columns.length)),def.columns);assert.deepEqual(copy(target.tables.Meals.columns.slice(-2).map(c=>c.name)),['preset_id','preset_revision'])});
test('migration keeps old IDs revisions ledger and source immutable',()=>{const books=Object.fromEntries(Object.keys(p3.tables).map(t=>[t,[]]));for(const table of ['Meals','MealItems','Operations','UndoValues','TrainingCycles'])books[table]=[Object.fromEntries(p3.tables[table].columns.map(c=>[c.name,c.nullable?null:c.type==='string'?c.name==='id'?id(1):'synthetic':c.type==='boolean'?false:1]))];const before=copy(books),plan=ctx.hubP4MigrationPlan_(p3,books);assert.deepEqual(books,before);for(const table of Object.keys(books))for(const row of books[table])for(const key of Object.keys(row))assert.deepEqual(plan.books[table][0][key],row[key]);assert.equal(plan.books.Meals[0].preset_id,null);assert.equal(plan.books.FoodVersions.length,0)});
test('migration rejects missing tables duplicate IDs unknown keys and invalid numbers',()=>{const books=Object.fromEntries(Object.keys(p3.tables).map(t=>[t,[]]));const missing=copy(books);delete missing.Operations;assert.throws(()=>ctx.hubP4MigrationPlan_(p3,missing),/MIGRATION_TABLE_SET/);const row=Object.fromEntries(p3.tables.Settings.columns.map(c=>[c.name,c.nullable?null:c.type==='string'?'synthetic':c.type==='boolean'?false:1]));for(const change of [rows=>rows.push(copy(rows[0])),rows=>rows[0].extra=true,rows=>rows[0].revision=Infinity]){const invalid=copy(books);invalid.Settings=[copy(row)];change(invalid.Settings);assert.throws(()=>ctx.hubP4MigrationPlan_(p3,invalid),/MIGRATION_/)} });
test('multi-item meal partial known sums preserve missing and real zero',()=>{const result=ctx.hubP4Transition_(empty(),operation());assert.equal(result.totals['2026-10-02'].known.kcal,100);assert.equal(result.totals['2026-10-02'].missing.kcal,1);assert.equal(result.totals['2026-10-02'].known.fat,0);assert.equal(result.totals['2026-10-02'].missing.fat,0)});
test('retry returns original committed and changed same ID rejected',()=>{const op=operation(),a=ctx.hubP4Transition_(empty(),op),b=ctx.hubP4Transition_(a.state,op);assert.equal(b.state.records.length,1);assert.deepEqual(copy(a.receipt),copy(b.receipt));const changed=copy(op);changed.payload.items[0].quantity=2;assert.throws(()=>ctx.hubP4Transition_(a.state,changed),/OPERATION_ID_REUSED/)});
test('quantity move and removal recompute both days',()=>{const a=ctx.hubP4Transition_(empty(),operation()),m=copy(a.state.records[0]);m.revision=2;m.date='2026-10-03';m.slot='間食';m.items[0].quantity=2;m.items[0].nutrients.kcal=200;const b=ctx.hubP4Transition_(a.state,operation(m,101));assert.equal(b.totals['2026-10-02'].known.kcal,0);assert.equal(b.totals['2026-10-03'].known.kcal,200);m.revision=3;m.removed=true;const c=ctx.hubP4Transition_(b.state,operation(m,102));assert.equal(c.totals['2026-10-03'].known.kcal,0)});
test('stale revision incomplete approval real data and invalid snapshot never mutate',()=>{const op=operation(),saved=ctx.hubP4Transition_(empty(),op).state,before=copy(saved);const stale=operation(meal(),102);assert.throws(()=>ctx.hubP4Transition_(saved,stale),/REVISION_CONFLICT/);for(const change of [o=>o.approval_state='draft',o=>o.synthetic=false,o=>o.environment='PHH_TEST',o=>o.payload.items[0].nutrients.kcal=-1,o=>o.payload.items[0].quantity=0,o=>o.payload.items[0].confidence='最高',o=>o.payload.items.push(copy(o.payload.items[0]))]){const bad=operation(meal(),103);change(bad);assert.throws(()=>ctx.hubP4Transition_(empty(),bad));}assert.deepEqual(copy(saved),before)});
test('same JSON fixture accepted by Swift and GAS retains snapshot references',()=>{const op=JSON.parse(fs.readFileSync(__dirname+'/food-p4-fixture.json','utf8'));const result=ctx.hubP4Transition_(empty(),op);assert.equal(result.state.records[0].presetRevision,1);assert.equal(result.state.records[0].items[0].versionID,op.payload.items[0].versionID);assert.equal(result.totals['2026-10-02'].missing.kcal,1)});
test('row plan preserves snapshot item order IDs revision and missing nutrient values',()=>{
 const m=meal(),before=copy(m),plan=copy(ctx.hubP4MealRows_(m,'PHH_PRODUCTION',id(100),Date.parse('2026-10-02T00:00:00Z')));
 assert.deepEqual(m,before);assert.equal(plan.rows.length,11);const items=plan.rows.filter(r=>r.table==='MealItems');assert.deepEqual(items.map(r=>r.record.id),m.items.map(i=>i.id));assert.deepEqual(items.map(r=>r.record.number),[1,2]);
 assert.equal(plan.known.kcal,100);assert.equal(plan.missing.kcal,1);assert.ok(plan.rows.every(r=>r.record.revision===1 && r.record.last_operation_id===id(100)));
 m.revision=2;m.removed=true;const removed=copy(ctx.hubP4MealRows_(m,'PHH_PRODUCTION',id(101),Date.parse('2026-10-03T00:00:00Z'),1,'2026-10-02T00:00:00Z'));assert.ok(removed.rows.every(r=>r.record.status==='removed' && r.record.created_at==='2026-10-02T00:00:00Z'));assert.equal(removed.known.kcal,0);
});
if(process.argv.includes('--rows')) {
 const op=JSON.parse(fs.readFileSync(__dirname+'/food-p4-fixture.json','utf8'));
 const plan=copy(ctx.hubP4MealRows_(op.payload,op.environment,op.operation_id,Date.parse('2026-10-02T00:00:00Z')));
 fs.writeFileSync(__dirname+'/food-p4-rows-fixture.json',JSON.stringify(plan.rows,null,2)+'\n');
}
if(process.argv.includes('--schema'))fs.writeFileSync(__dirname+'/../Core/Sources/PHHHubCore/Resources/food-p4-schema.json',JSON.stringify(copy(ctx.hubP4Schema_(p3)),null,2)+'\n');
console.log(`food-p4: ${passed} passed`);
