// P6-4：gzip原本もバックアップ世代内へ複製し、別先復元では新file_idへ付け替えます。
function hubHealthBackupRefs_(tables) {
  const refs=new Map();for(const table of ['HealthBatches','HealthArchives','HealthPreparations'])for(const row of tables[table] || [])if(row.file_id && row.gzip_bytes>0){const prior=refs.get(row.file_id);const meta=Object.fromEntries(['file_id','raw_sha256','gzip_sha256','raw_bytes','gzip_bytes','record_count'].map(k=>[k,row[k]]));if(prior)ensure_(stable_(meta)===stable_(prior),'HEALTH_BACKUP_FILE_REFERENCE');else refs.set(row.file_id,meta);}
  return [...refs.values()].sort((a,b)=>a.file_id.localeCompare(b.file_id));
}
function hubHealthBackupValidate_(tables,meta) {
  const hash=v=>typeof v==='string' && /^[a-f0-9]{64}$/.test(v),files=hubHealthBackupRefs_(tables);
  for(const file of files)ensure_(hash(file.raw_sha256) && hash(file.gzip_sha256) && Number.isSafeInteger(file.raw_bytes) && file.raw_bytes>0 && file.raw_bytes<=200*1024 && Number.isSafeInteger(file.gzip_bytes) && file.gzip_bytes>0 && file.gzip_bytes<=250000 && Number.isSafeInteger(file.record_count) && file.record_count>0 && file.record_count<=500,'HEALTH_BACKUP_FILE_META');
  for(const batch of tables.HealthBatches){hubHealthMetric_(batch.metric);ensure_(batch.id===batch.last_operation_id && batch.revision===1 && batch.status==='active' && tables.Operations.some(o=>o.id===batch.id && o.status==='committed' && o.action==='save_health_delta' && o.content_hash===batch.request_hash) && [batch.added_count,batch.deleted_count,batch.statistics_count].every(n=>Number.isSafeInteger(n) && n>=0) && batch.added_count+batch.deleted_count+batch.statistics_count<=500 && batch.format_version===1,'HEALTH_BACKUP_BATCH');}
  for(const row of tables.HealthArchives){hubHealthMetric_(row.metric);ensure_(['samples','uuid_index','coverage'].includes(row.kind) && row.format_version===1 && row.part_number>=1 && row.part_number<=100000 && Number.isSafeInteger(row.active_count) && row.active_count>=0 && row.active_count<=row.record_count,'HEALTH_BACKUP_ARCHIVE');if(row.kind==='samples')ensure_(row.source_id && row.local_date && row.partition_key===hubHealthSampleKey_(row.metric,intakeDate_(row.local_date),row.source_id) && row.id===hubHealthArchiveId_({config:{environment:meta.environment}},row.partition_key,row.part_number),'HEALTH_BACKUP_ARCHIVE');else if(row.kind==='coverage'){const primary=tables.HealthArchives.find(r=>r.id===row.partition_key.slice(9));ensure_(row.partition_key.startsWith('coverage|') && primary?.kind==='samples' && row.metric===primary.metric && row.source_id===primary.source_id && row.local_date!==primary.local_date && row.id===hubId_(meta.environment+'|health-coverage|'+primary.id+'|'+intakeDate_(row.local_date)) && row.file_id===primary.file_id,'HEALTH_BACKUP_COVERAGE');}else ensure_(row.source_id===null && row.local_date===null && new RegExp('^uuid\\|'+row.metric+'\\|[a-f0-9]{2,64}$').test(row.partition_key) && row.id===hubHealthArchiveId_({config:{environment:meta.environment}},row.partition_key),'HEALTH_BACKUP_ARCHIVE');if(row.status==='active')ensure_(row.file_id && row.gzip_bytes>0,'HEALTH_BACKUP_ARCHIVE');}
  for(const row of tables.HealthDaily){const metric=hubHealthMetric_(row.metric);intakeDate_(row.local_date);ensure_(['source-latest-v1','source-interval-union-v1','healthkit-statistics-v1'].includes(row.method) && (row.value===null || Number.isFinite(row.value) && row.value>=0) && Number.isSafeInteger(row.known_count) && row.known_count>=0 && Number.isSafeInteger(row.unknown_count) && row.unknown_count>=0 && row.sample_revision>0,'HEALTH_BACKUP_DAILY');if(metric.cumulative)ensure_(row.source_id===null && row.unit===metric.unit && row.method==='healthkit-statistics-v1' && row.minimum===null && row.maximum===null && row.representative_id===null && row.id===hubId_(meta.environment+'|health-day|'+row.metric+'|'+row.local_date+'|statistics'),'HEALTH_BACKUP_DAILY');else ensure_(row.source_id && row.id===hubId_(meta.environment+'|health-day|'+row.metric+'|'+row.local_date+'|'+row.source_id) && row.unit===(row.metric==='sleepAnalysis'?'s':metric.unit) && row.method===(row.metric==='sleepAnalysis'?'source-interval-union-v1':'source-latest-v1'),'HEALTH_BACKUP_DAILY');}
  for(const row of tables.HealthPreparations){ensure_(hubIsId_(row.operation_id) && hash(row.request_hash) && ['samples','uuid_index','batch'].includes(row.kind) && ['prepared','committed'].includes(row.stage),'HEALTH_BACKUP_PREPARATION');if(row.stage==='committed')ensure_(tables.Operations.some(o=>o.id===row.operation_id && o.status==='committed' && o.content_hash===row.request_hash) && row.file_id,'HEALTH_BACKUP_PREPARATION');}
  for(const table of ['HealthBatches','HealthArchives','HealthDaily'])for(const row of tables[table]){const latest=tables.SyncChanges.filter(c=>c.table_name===table && c.entity_id===row.id && c.revision===row.revision).sort((a,b)=>b.change_number-a.change_number)[0];ensure_(latest && latest.operation_id===row.last_operation_id,'HEALTH_BACKUP_OPERATION_LINK');}
}
function hubHealthBackupAttach_(bundle,tables,reader) {
  const files=hubHealthBackupRefs_(tables),objects={...bundle.objects};for(const meta of files){const blob=reader(meta);hubHealthReadBlob_(blob,meta);objects['gzip:'+meta.gzip_sha256]=Utilities.base64Encode(blob.getBytes());}
  const manifest=hubClone_(bundle.manifest);delete manifest.id;delete manifest.sha256;manifest.health_files=files;manifest.sha256=hubHash_(manifest);manifest.id=hubId_(manifest.sha256);hubHealthBackupVerifyFiles_(manifest,objects,tables);return {manifest,objects};
}
function hubHealthBackupCapture_(bundle,tables,config) {
  if(!hubHealthBackupRefs_(tables).length)return bundle;
  const folder=hubHealthFolder_(config);return hubHealthBackupAttach_(bundle,tables,meta=>{const file=DriveApp.getFileById(meta.file_id);hubBackupPrivate_(file,config.owner);hubHealthBelongs_(file,folder);return file.getBlob();});
}
function hubHealthBackupVerifyFiles_(manifest,objects,tables) {
  const refs=hubHealthBackupRefs_(tables);ensure_(stable_(refs)===stable_((manifest.health_files || []).slice().sort((a,b)=>a.file_id.localeCompare(b.file_id))),'HEALTH_BACKUP_FILE_REFERENCE');
  const byFile=new Map(refs.map(r=>[r.file_id,r])),cache=new Map(),read=id=>{if(cache.has(id)){const rows=cache.get(id);cache.delete(id);cache.set(id,rows);return rows;}const meta=byFile.get(id);ensure_(meta,'HEALTH_BACKUP_FILE_MISSING');const encoded=objects['gzip:'+meta.gzip_sha256];ensure_(typeof encoded==='string','HEALTH_BACKUP_FILE_MISSING');let bytes;try{bytes=Utilities.base64Decode(encoded);}catch(e){throw Error('HEALTH_BACKUP_FILE_HASH');}const rows=hubHealthReadBlob_(Utilities.newBlob(bytes,'application/gzip'),meta);cache.set(id,rows);if(cache.size>8)cache.delete(cache.keys().next().value);return rows;};for(const meta of refs)read(meta.file_id);
  const sampleParts=new Map();for(const p of tables.HealthArchives || [])if(p.kind==='samples' && p.status==='active') {
    const rows=read(p.file_id);ensure_(rows && rows.length===p.record_count && rows.filter(r=>!r.removed).length===p.active_count,'HEALTH_BACKUP_ARCHIVE_CONTENT');const ids=new Set();for(const r of rows){hubKeys_(r,['id','metric','removed','sample']);ensure_(hubIsId_(r.id) && r.metric===p.metric && typeof r.removed==='boolean' && !ids.has(r.id) && (r.removed?r.sample===null:r.sample && r.sample.id===r.id),'HEALTH_BACKUP_ARCHIVE_CONTENT');ids.add(r.id);if(!r.removed){const s=hubHealthValidateSample_(r.sample,p.metric);ensure_(s.source.id===p.source_id && hubHealthAffectedDates_(s)[0]===p.local_date,'HEALTH_BACKUP_ARCHIVE_CONTENT');}}sampleParts.set(p.id,p);
  }
  const indexParts=new Map();for(const p of tables.HealthArchives || [])if(p.kind==='uuid_index' && p.status==='active') {
    ensure_(!indexParts.has(p.partition_key),'HEALTH_BACKUP_INDEX');indexParts.set(p.partition_key,p);const rows=read(p.file_id),ids=new Set();ensure_(rows && rows.filter(r=>!r.removed).length===p.active_count,'HEALTH_BACKUP_INDEX');for(const r of rows){hubKeys_(r,['id','metric','removed','archive_id']);ensure_(hubIsId_(r.id) && r.metric===p.metric && typeof r.removed==='boolean' && !ids.has(r.id) && p.partition_key===hubHealthIndexKey_(r.metric,hubHash_(r.id).slice(0,p.partition_key.split('|')[2].length)),'HEALTH_BACKUP_INDEX');ids.add(r.id);if(r.archive_id){const primary=sampleParts.get(r.archive_id),sample=primary && read(primary.file_id).find(s=>s.id===r.id);ensure_(sample && sample.removed===r.removed,'HEALTH_BACKUP_INDEX');}else ensure_(r.removed,'HEALTH_BACKUP_INDEX');}
  }
  for(const part of sampleParts.values())for(const r of read(part.file_id)){const hash=hubHash_(r.id);let entry;for(let len=2;len<=64;len++){const ix=indexParts.get(hubHealthIndexKey_(r.metric,hash.slice(0,len)));if(ix){entry=read(ix.file_id).find(e=>e.id===r.id);break;}}ensure_(entry?.archive_id===part.id && entry.removed===r.removed,'HEALTH_BACKUP_INDEX');}
  for(const part of sampleParts.values())for(const r of read(part.file_id).filter(r=>!r.removed))for(const date of hubHealthAffectedDates_(r.sample).filter(d=>d!==part.local_date)){const alias=tables.HealthArchives.find(p=>p.kind==='coverage' && p.partition_key==='coverage|'+part.id && p.local_date===date);ensure_(alias?.status==='active' && alias.active_count>0,'HEALTH_BACKUP_COVERAGE_MISSING');}
  for(const p of tables.HealthArchives || [])if(p.kind==='coverage' && p.status==='active')ensure_(read(p.file_id).filter(r=>!r.removed && hubHealthAffectedDates_(r.sample).includes(p.local_date)).length===p.active_count,'HEALTH_BACKUP_COVERAGE');
  for(const b of tables.HealthBatches || []){const body=read(b.file_id);ensure_(body?.length===1 && body[0].id===b.id && body[0].metric===b.metric && body[0].added.length===b.added_count && body[0].deletedIDs.length===b.deleted_count && (body[0].statistics || []).length===b.statistics_count,'HEALTH_BACKUP_BATCH');hubHealthValidateDelta_({schema_version:1,environment:manifest.environment,synthetic:true,operation_id:b.id,entity_id:b.id,expected_revision:0,action:'save_health_delta',approval_state:'confirmed',payload:body[0]},{environment:manifest.environment,real_data_enabled:false});}
  for(const day of tables.HealthDaily || []) {
    let expected;if(hubHealthMetric_(day.metric).cumulative){const batch=tables.HealthBatches.find(b=>b.id===day.last_operation_id && b.metric===day.metric);ensure_(batch,'HEALTH_BACKUP_DAILY_CONTENT');const delta=read(batch.file_id)[0],stat=(delta.statistics || []).find(s=>s.date===day.local_date);expected={value:stat?.value ?? null,measured_at_utc:stat?.measured_at_utc ?? null,known_count:stat?.value!=null?1:0,unknown_count:stat?.value!=null?0:1,minimum:null,maximum:null,representative_id:null};}
    else {const selected=new Map();for(const p of tables.HealthArchives.filter(p=>['samples','coverage'].includes(p.kind) && p.status==='active' && p.local_date===day.local_date && p.metric===day.metric && p.source_id===day.source_id)){const primary=p.kind==='coverage'?sampleParts.get(p.partition_key.slice(9)):p;ensure_(primary,'HEALTH_BACKUP_COVERAGE');selected.set(primary.id,primary);}expected=hubHealthBackupDailyStream_(day,[...selected.values()],read);}
    for(const key of ['value','measured_at_utc','known_count','unknown_count','minimum','maximum','representative_id'])ensure_(stable_(day[key])===stable_(expected[key]),'HEALTH_BACKUP_DAILY_CONTENT');
  }
  return {verified_files:refs.length};
}
function hubHealthBackupDailyStream_(day,parts,read) {
  const out={value:null,measured_at_utc:null,known_count:0,unknown_count:0,minimum:null,maximum:null,representative_id:null};let latest=null,intervals=[];
  for(const p of parts)for(const row of read(p.file_id))if(!row.removed && hubHealthAffectedDates_(row.sample).includes(day.local_date)){const s=row.sample;if(day.metric==='sleepAnalysis'){out.known_count++;if(['inBed','awake'].includes(s.sleepStage))continue;let start=s.start_utc,end=s.end_utc;const kept=[];for(const interval of intervals){if(interval[1]<start || interval[0]>end)kept.push(interval);else {start=Math.min(start,interval[0]);end=Math.max(end,interval[1]);}}kept.push([start,end]);intervals=kept.sort((a,b)=>a[0]-b[0]);}else{if(s.value===null)out.unknown_count++;else{out.known_count++;out.minimum=out.minimum===null?s.value:Math.min(out.minimum,s.value);out.maximum=out.maximum===null?s.value:Math.max(out.maximum,s.value);}if(!latest || s.start_utc>latest.start_utc || s.start_utc===latest.start_utc && s.id.localeCompare(latest.id)>0)latest={id:s.id,start_utc:s.start_utc,value:s.value};}}
  if(day.metric==='sleepAnalysis')out.value=out.known_count?intervals.reduce((n,[a,b])=>n+(b-a),0):null;else if(latest){out.value=latest.value;out.representative_id=latest.id;}return out;
}
function hubHealthBackupFileKey_(name) {return /^[a-f0-9]{64}\.jsonl\.gz$/.test(name)?'gzip:'+name.slice(0,-9):null;}
function hubHealthBackupRestoreFiles_(bundle,folder,config) {
  const tables=hubBackupVerify_(bundle.manifest,bundle.objects);hubBackupPrivate_(folder,config.owner);const files=new Map(),adapter=hubHealthArchiveAdapter_(config,folder);
  for(const meta of bundle.manifest.health_files || []){const raw=hubHealthJSONL_(hubHealthReadBlob_(Utilities.newBlob(Utilities.base64Decode(bundle.objects['gzip:'+meta.gzip_sha256]),'application/gzip'),meta));const prep={id:hubId_(bundle.manifest.id+'|restore|'+meta.gzip_sha256)};const file=adapter.write(prep,raw);files.set(meta.file_id,file);}
  for(const name of ['HealthBatches','HealthArchives','HealthPreparations'])for(const row of tables[name] || [])if(files.has(row.file_id)){const file=files.get(row.file_id);for(const key of ['file_id','raw_sha256','gzip_sha256','raw_bytes','gzip_bytes','record_count'])row[key]=file[key];}
  // 新IDが正本・manifestに残るよう、table partsも別bundleとして再構築します。
  const rebuilt=hubBackupCreate_(tables,{environment:bundle.manifest.environment,start_generation:bundle.manifest.generation,end_generation:bundle.manifest.generation,start_revision:bundle.manifest.snapshot_revision,end_revision:bundle.manifest.snapshot_revision,now:Date.parse(bundle.manifest.created_at)});
  return hubHealthBackupAttach_(rebuilt,tables,meta=>DriveApp.getFileById(meta.file_id).getBlob());
}
function hubHealthRestoreFolder_(owner,target) {
  const props=PropertiesService.getScriptProperties(),key='PHH_HEALTH_RESTORE_FOLDER_'+target;let id=props.getProperty(key);
  if(!id){const folder=DriveApp.createFolder('Personal Health Hub — Separate Health Restore '+target);hubBackupPrivate_(folder,owner);id=folder.getId();props.setProperty(key,id);}
  const folder=DriveApp.getFolderById(id);hubBackupPrivate_(folder,owner);return folder;
}
