// 本番GASの純粋ルール/行別保存計画。実ファイル・認証へ接続しない。
const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const schema=JSON.parse(fs.readFileSync(__dirname+'/schema.json','utf8'));
const ctx=vm.createContext({console,Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,v)=>[...crypto.createHash('sha256').update(v).digest()],getUuid:()=>crypto.randomUUID(),newBlob:v=>({getBytes:()=>[...Buffer.from(v)]})}});
vm.runInContext('const HUB_SCHEMA_='+JSON.stringify(schema)+';'+['Core.gs','IntakeRules.gs','Storage.gs','Engine.gs','API.gs'].map(n=>fs.readFileSync(__dirname+'/'+n,'utf8')).join('\n'),ctx);
const copy=v=>JSON.parse(JSON.stringify(v));
class MemoryStore {
  constructor() {this.config={environment:'PHH_TEST',real_data_enabled:false};this.tables={};this.indexes={};this.pending=new Map();this.positions=new Map();this.reads=0;this.commits=0;this.fail=false;for(const name of Object.keys(schema.tables)){this.tables[name]=new Map();this.indexes[name]={};} }
  seed(table,row) {ctx.hubRow_(table,row);this.tables[table].set(row.id,copy(row));if(!this.positions.has(table+'\0'+row.id))this.positions.set(table+'\0'+row.id,this.tables[table].size+1);for(const col of schema.tables[table].columns){const ix=this.indexes[table][col.name] ||= new Map();if(!ix.has(row[col.name]))ix.set(row[col.name],new Set());ix.get(row[col.name]).add(row.id);} }
  prefetch(entries) { /* メモリ上の行は既に取得済み。クラウド側のまとめ読みだけを省く。 */ }
  get(table,id) {this.reads++;const v=this.pending.get(table+'\0'+id) || this.tables[table].get(id);return v?copy(v):null;}
  find(table,field,value) {const ids=this.indexes[table][field]?.get(value) || new Set(),out=new Map();for(const id of ids){const row=this.get(table,id);if(row && row[field]===value)out.set(id,row);}for(const [key,r] of this.pending)if(key.startsWith(table+'\0')){out.delete(r.id);if(r[field]===value)out.set(r.id,copy(r));}return [...out.values()];}
  put(table,row) {ctx.hubRow_(table,row);const k=table+'\0'+row.id;if(!this.positions.has(k)){const count=[...this.positions.keys()].filter(x=>x.startsWith(table+'\0')).length;this.positions.set(k,count+2);}this.pending.set(k,copy(row));}
  position(table,id) {return this.positions.get(table+'\0'+id);}
  all(table) {assert.ok(['Settings','IntakeLedger','IntakeScans','Reviews'].includes(table),'all-year business body read forbidden');const out=new Map(this.tables[table]);for(const [k,r] of this.pending)if(k.startsWith(table+'\0'))out.set(r.id,copy(r));return [...out.values()];}
  range(table,start,count) {return Array.from({length:count},(_,i)=>this.get(table,String(start+i-1))).filter(Boolean);}
  commit() {if(this.fail){this.pending.clear();throw Error('STORAGE_UNAVAILABLE');}for(const [key,r] of this.pending){const table=key.split('\0')[0],old=this.tables[table].get(r.id);if(old)for(const col of schema.tables[table].columns)this.indexes[table][col.name]?.get(old[col.name])?.delete(r.id);this.seed(table,r);}this.pending.clear();this.commits++;}
}
let passed=0;function test(name,body){body();passed++;console.log('ok '+name);}
const now=Date.parse('2026-10-01T12:00:00Z');
function fresh(){const s=new MemoryStore();for(const [k,v]of Object.entries({environment:'PHH_TEST',schema_version:1,real_data_enabled:false,next_change:0,generation:1,next_inbox_row:2,audit_row:2,publication_dirty:false}))ctx.hubSet_(s,k,v,now);s.commit();return s;}
function intake(s,row,n,time=now){const r=ctx.hubProcessIntakeRow_(s,row,n,time);s.commit();return r;}
function meal(action='confirm_meal',entity=crypto.randomUUID(),revision=0,payload={local_date:'2026-10-01',slot:'昼食',name:'架空の食事',quantity:1,unit:'食',kcal:100,protein_g:10,fat_g:0,carbohydrate_g:null,source:'本人'}){return {schema_version:1,environment:'PHH_TEST',synthetic:true,approval_state:'confirmed',operation_id:crypto.randomUUID(),entity_id:entity,expected_revision:revision,action,payload};}
function app(s,op,time=now){const r=ctx.hubApplyApp_(s,op,time);s.commit();return copy(r);}
const set=(id='s1',reps=8)=>[id,'記録','筋トレ','2026-10-01','Pull','ダンベルカール','1','重量kg=10; 回数='+reps,''];
test('B2 normal set and omitted RPE',()=>{const s=fresh(),r=intake(s,set(),2);assert.equal(r.status,'保存済み');const rec=s.tables.TrainingSets.get(r.record_id);assert.equal(rec.rpe,null);assert.equal(rec.rir,null);assert.equal(s.tables.TrainingSessions.size,1);assert.ok(ctx.hubIsId_(rec.id));});
test('B2 same id/body replays once',()=>{const s=fresh();const a=intake(s,set(),2),b=intake(s,set(),2),c=intake(s,set(),3);assert.equal(b.status,'保存済み');assert.equal(c.status,'重複');assert.equal(c.duplicate,true);assert.equal(s.tables.TrainingSets.size,1);assert.equal(s.tables.Operations.size,1);assert.equal(a.record_id,b.record_id || a.record_id);});
test('B2 reused id is review, never overwrites',()=>{const s=fresh();const a=intake(s,set(),2);assert.equal(intake(s,set('s1',10),3).status,'要確認');assert.equal(s.tables.TrainingSets.get(a.record_id).reps,8);assert.equal([...s.tables.Reviews.values()][0].reason,'ID_REUSED');});
test('B2 edited accepted row is review once',()=>{const s=fresh();const a=intake(s,set(),2);intake(s,set('s1',99),2);intake(s,set('s1',99),2);assert.equal(s.tables.Reviews.size,1);assert.equal(s.tables.TrainingSets.get(a.record_id).reps,8);assert.equal([...s.tables.Reviews.values()][0].reason,'ROW_EDITED');});
test('B2 incomplete completion, then ten-minute review',()=>{const s=fresh();assert.equal(intake(s,['pending','記録','筋トレ','','','','','',''],2).status,'保留');assert.equal(intake(s,set('pending'),2,now+1000).status,'保存済み');assert.equal(intake(s,['wait','記録','筋トレ','','','','','',''],3).status,'保留');assert.equal(intake(s,['wait','記録','筋トレ','','','','','',''],3,now+600001).status,'要確認');});
test('B2 missing/invalid/duplicate targets do not save',()=>{const s=fresh();assert.equal(intake(s,set('bad',-1),2).status,'要確認');intake(s,set('ok'),3);assert.equal(intake(s,set('dup'),4).status,'要確認');assert.equal(intake(s,['miss','修正','筋トレ','2026-10-01','Pull','別種目','1','回数=10',''],5).status,'要確認');assert.equal(s.tables.TrainingSets.size,1);});
test('B2 ambiguous meal needs number',()=>{const s=fresh();const r=id=>[id,'記録','食事','2026-10-01','昼食','同名','','量=1; 単位=食; kcal=100',''];intake(s,r('m1'),2);intake(s,r('m2'),3);assert.equal(intake(s,['m3','修正','食事','2026-10-01','昼食','同名','','量=2',''],4).status,'要確認');assert.equal(s.tables.Meals.size,2);});
test('B2 proportional quantity and unknown distinct from zero',()=>{const s=fresh();const r=intake(s,['m1','記録','食事','2026-10-01','昼食','同名','','量=1; 単位=食; kcal=100; F=0',''],2);assert.equal(intake(s,['m2','修正','食事','2026-10-01','昼食','同名','1','量=2',''],3).status,'保存済み');const day=s.tables.DailySummary.get('2026-10-01');assert.equal(day.kcal,200);assert.equal(day.fat_g,0);assert.equal(day.fat_unknown,0);assert.equal(day.protein_unknown,1);assert.equal([...s.tables.IntakeNutrients.values()].find(n=>n.nutrient_id==='protein_g').value,null);});
test('B2 app edit protected then stale app conflicts',()=>{const s=fresh(),op=meal();app(s,op);app(s,meal('update_meal',op.entity_id,1,{kcal:200}),now+1);assert.equal(intake(s,['b','修正','食事','2026-10-01','昼食','架空の食事','1','kcal=300',''],2,now+2).status,'要確認');assert.equal(s.tables.DailySummary.get('2026-10-01').kcal,200);assert.equal(app(s,meal('update_meal',op.entity_id,1,{kcal:400}),now+3).error_code,'REVISION_CONFLICT');});
test('B2 note remains through cancel and undo, persisted fields',()=>{const s=fresh(),r=intake(s,set(),2);intake(s,['n','補足','筋トレ','2026-10-01','Pull','ダンベルカール','','分類=身体状態; 発言者=本人','架空メモ'],3);intake(s,['c','取消','筋トレ','2026-10-01','Pull','ダンベルカール','1','',''],4);assert.equal(s.tables.TrainingSets.get(r.record_id).status,'removed');assert.equal(s.tables.TrainingNotes.size,1);assert.equal(intake(s,['u','戻す','筋トレ','','','','','対象受付番号=c',''],5).status,'保存済み');assert.equal(s.tables.TrainingSets.get(r.record_id).reps,8);assert.equal(s.tables.TrainingSets.get(r.record_id).revision,3);assert.equal(s.tables.IntakeLedger.get('c').undone,true);assert.equal(intake(s,['u2','戻す','筋トレ','','','','','対象受付番号=c',''],6).status,'要確認');});
test('B2 undo blocked by later edit, unknown field rejected',()=>{const s=fresh();intake(s,set(),2);intake(s,['fix','修正','筋トレ','2026-10-01','Pull','ダンベルカール','1','回数=10',''],3);intake(s,['fix2','修正','筋トレ','2026-10-01','Pull','ダンベルカール','1','回数=12',''],4);assert.equal(intake(s,['u','戻す','筋トレ','','','','','対象受付番号=fix',''],5).status,'要確認');assert.equal(intake(s,['unknown','修正','筋トレ','2026-10-01','Pull','ダンベルカール','1','謎=1',''],6).status,'要確認');});
test('A create/replay/update/move/delete and both day aggregates',()=>{const s=fresh(),op=meal();const first=app(s,op);assert.deepEqual(app(s,op),first);assert.equal(s.tables.Meals.size,1);app(s,meal('update_meal',op.entity_id,1,{quantity:2}));assert.equal(s.tables.DailySummary.get('2026-10-01').kcal,200);app(s,meal('update_meal',op.entity_id,2,{local_date:'2026-10-02'}));assert.equal(s.tables.DailySummary.get('2026-10-01').kcal,0);assert.equal(s.tables.DailySummary.get('2026-10-02').kcal,200);app(s,meal('remove_meal',op.entity_id,3,null));assert.equal(s.tables.DailySummary.get('2026-10-02').kcal,0);assert.equal(s.tables.Meals.get(op.entity_id).status,'removed');assert.ok([...s.tables.IntakeNutrients.values()].every(n=>n.status==='removed'));});
test('A invalid/nan/unconfirmed/changed operation id',()=>{const s=fresh(),op=meal();app(s,op);assert.throws(()=>app(s,{...op,payload:{...op.payload,kcal:200}}),/OPERATION_ID_REUSED/);const bad=meal();bad.payload.quantity=NaN;assert.equal(app(s,bad).status,'rejected');const unconfirmed=meal();unconfirmed.approval_state='draft';assert.equal(app(s,unconfirmed).error_code,'CONFIRMATION_REQUIRED');assert.equal(s.tables.Meals.size,1);});
test('environment and real-data gates before writes',()=>{const s=fresh(),op=meal();assert.throws(()=>app(s,{...op,environment:'PHH_PRODUCTION'}),/ENVIRONMENT_MISMATCH/);assert.throws(()=>app(s,{...op,synthetic:false}),/REAL_DATA_DISABLED/);assert.equal(s.tables.Meals.size,0);});
test('store failure atomically leaves record/ledger/index/summary absent',()=>{const s=fresh(),op=meal();ctx.hubApplyApp_(s,op,now);s.fail=true;assert.throws(()=>s.commit(),/STORAGE_UNAVAILABLE/);for(const table of ['Meals','MealItems','IntakeNutrients','Operations','SyncChanges','DailySummary'])assert.equal(s.tables[table].size,0);s.fail=false;const r=app(s,op);assert.equal(r.status,'committed');assert.equal(s.tables.Meals.size,1);});
test('delta pagination preserves ids and tombstones; generation and snapshot reject',()=>{const s=fresh(),op=meal();app(s,op);const q={schema_version:1,environment:'PHH_TEST',synthetic:true,after:0,limit:2,generation:1};const a=ctx.hubChanges_(s,q);assert.equal(a.changes.length,2);assert.equal(a.has_more,true);let next=a.next_cursor,count=2;while(next<a.snapshot_revision){const b=ctx.hubChanges_(s,{...q,after:next,snapshot_revision:a.snapshot_revision});assert.ok(b.next_cursor>next);next=b.next_cursor;count+=b.changes.length;}assert.equal(count,a.snapshot_revision);app(s,meal('remove_meal',op.entity_id,1,null));const b=ctx.hubChanges_(s,{...q,after:a.snapshot_revision,limit:500});assert.ok(b.changes.filter(c=>c.change.table_name!=='DailySummary').every(c=>c.change.removed));assert.throws(()=>ctx.hubChanges_(s,{...q,generation:0}),/CURSOR_EXPIRED/);assert.throws(()=>ctx.hubChanges_(s,{...q,snapshot_revision:a.snapshot_revision}),/SNAPSHOT_CHANGED/);});
test('bounded new/pending/audit selection over long intake',()=>{const s=fresh();ctx.hubSet_(s,'next_inbox_row',10000,now);ctx.hubSet_(s,'audit_row',100,now);s.commit();const touched=[];const r=ctx.hubPollWork_(s,row=>{touched.push(row);return ['', '', '', '', '', '', '', '', ''];},10009,now);assert.equal(r.processed,30);assert.equal(Math.min(...touched),100);assert.equal(Math.max(...touched),10009);assert.equal(ctx.hubSetting_(s,'next_inbox_row'),10010);assert.equal(ctx.hubSetting_(s,'audit_row'),120);});
test('typed write cells and pointers reject wrong types/formula injection',()=>{assert.deepEqual(copy(ctx.hubCell_('=IMPORTXML("x")')),{userEnteredValue:{stringValue:'=IMPORTXML("x")'}});assert.deepEqual(copy(ctx.hubCell_(0)),{userEnteredValue:{numberValue:0}});assert.throws(()=>ctx.hubRow_('Operations',{id:'x',content_hash:'h',actor:'a',action:'a',status:'committed',error_code:null,committed_at:'t',change_number:'1'}),/COLUMN_TYPE/);});
test('C3 unchanged fixture, all row outcomes and public summaries survive the row store',()=>{const fixture=JSON.parse(fs.readFileSync(__dirname+'/../../Probe/ServerAccess/intake-c3-fixture.json','utf8')),s=fresh();let next=2;for(const batch of fixture.batches){if(batch.action==='append'){const outcomes=batch.rows.map(row=>intake(s,row,next++).status);assert.deepEqual(outcomes,batch.expected_status);}else {const result=intake(s,batch.row,batch.sheet_row);assert.equal(result.status,'要確認');}}assert.equal(s.tables.Reviews.size,3);for(const date of ['2026-10-01','2026-09-30']){const state=ctx.hubEmptyState_();ctx.hubLoadDate_(s,date,state);state.reviews=[...s.tables.Reviews.values()];const text=ctx.intakeSummaryForHub_(state,date,now);for(const expected of fixture.expected_final['summary_'+date+'_contains'] || [])assert.ok(text.includes(expected),expected);for(const excluded of fixture.expected_final['summary_'+date+'_not_contains'] || [])assert.ok(!text.includes(excluded),excluded);}});
test('derived nutrient overflow does not partially save a B2 edit',()=>{const s=fresh();intake(s,['a','記録','食事','2026-10-01','昼食','架空','','量=1; 単位=食; kcal=10000',''],2);assert.equal(intake(s,['b','修正','食事','2026-10-01','昼食','架空','1','量=2',''],3).status,'要確認');assert.equal(s.tables.DailySummary.get('2026-10-01').kcal,10000);});
// 一年分相当の索引を種として、触る日だけを読む処理を計測。GASの実通信時間とは別。
test('year-size index, cold bounded day processing below ten seconds',()=>{const s=fresh();const total=35040;for(let i=0;i<total;i++){const id=crypto.randomUUID();const date='2025-'+String(Math.floor(i/2920)+1).padStart(2,'0')+'-'+String(i%28+1).padStart(2,'0');if(!s.tables.TrainingSessions.has(ctx.hubId_(date)))s.seed('TrainingSessions',{id:ctx.hubId_(date),revision:1,status:'active',created_at:'2025-01-01T00:00:00Z',updated_at:'2025-01-01T00:00:00Z',source_kind:'conversation',last_operation_id:crypto.randomUUID(),local_date:date,time_zone:'Asia/Tokyo',session:'Pull',cycle_id:null,started_at:null,ended_at:null});s.seed('TrainingSets',{id,revision:1,status:'active',created_at:'2025-01-01T00:00:00Z',updated_at:'2025-01-01T00:00:00Z',source_kind:'conversation',last_operation_id:crypto.randomUUID(),session_id:ctx.hubId_(date),exercise:'架空種目'+i,set_no:1,weight_kg:10,reps:8,rpe:null,rir:null,weight_basis:'通常',occurred_at:null});s.seed('RecordIndex',{id,table_name:'TrainingSets',sheet_row:i+2,local_date:date,lookup_key:'seed|'+i,parent_id:ctx.hubId_(date),revision:1,status:'active'});}s.reads=0;const start=performance.now();const r=intake(s,set('year'),2);const ms=performance.now()-start;assert.equal(r.status,'保存済み');assert.ok(ms<10000);assert.ok(s.reads<200,'one-year record bodies not read');console.log('year_index='+total+' elapsed_ms='+ms.toFixed(2)+' bounded_reads='+s.reads);});
console.log('Hub server: '+passed+' PASSED');
