// 既存の行ストア試験と同じメモリストアを使い、P3拡張だけを有効化する。
const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto');
const source=fs.readFileSync(__dirname+'/server-test.cjs','utf8').split("test('B2 normal set")[0],harness={exports:{}};
new Function('require','module','__dirname',source+'\nmodule.exports={ctx,schema,MemoryStore,fresh,intake,app,meal,now,copy};')(require,harness,__dirname);
const {ctx,schema,fresh,intake,app,meal,now,copy}=harness.exports;
vm.runInContext(fs.readFileSync(__dirname+'/TrainingP3.gs','utf8'),ctx);
const baseline=copy(schema);Object.assign(schema,copy(ctx.hubP3Schema_(baseline)));vm.runInContext('Object.assign(HUB_SCHEMA_,hubP3Schema_(HUB_SCHEMA_))',ctx);
let passed=0;function test(name,fn){fn();passed++;console.log('ok '+name);}
const cycleOp=()=>({...meal(),action:'register_training_cycle',payload:{name:'架空Cycle',source_path:'synthetic-plan.md',source_sha256:'a'.repeat(64),slots:Array.from({length:9},(_,i)=>({number:i+1,label:['Push-A','Pull-A','Leg-A'][i%3],kind:['Push','Pull','Leg'][i%3]}))}});
const row=(id,kind,session='Pull',name='ダンベルカール',no='1',content='重量kg=10; 回数=8',text='')=>[id,kind,'筋トレ','2026-10-02',session,name,no,content,text];
test('cycle reference and nine slots commit and replay unchanged',()=>{const s=fresh(),op=cycleOp(),a=app(s,op),b=app(s,op);assert.deepEqual(a,b);assert.equal(s.tables.TrainingCycles.size,1);assert.equal(s.tables.TrainingPlanSlots.size,9);assert.equal(a.entity_ids[0],op.entity_id);assert.equal(s.tables.Operations.size,1);assert.equal(s.tables.TrainingCycles.get(op.entity_id).source_sha256,'a'.repeat(64));});
test('bad last slot, body injection and conflict do not partially write',()=>{const s=fresh(),op=cycleOp();op.payload.slots[8].number=8;assert.equal(app(s,op).status,'rejected');assert.equal(s.tables.TrainingCycles.size,0);assert.equal(s.tables.TrainingPlanSlots.size,0);const x=cycleOp();x.payload.markdown='do not store';assert.equal(app(s,x).error_code,'UNKNOWN_FIELD');const good=cycleOp();app(s,good);assert.equal(app(s,{...good,operation_id:crypto.randomUUID()}).error_code,'ENTITY_EXISTS');});
test('all exercises, same day sessions and four categories preserve IDs',()=>{const s=fresh(),a=intake(s,row('a','記録'),2);intake(s,row('b','記録','Pull2'),3);intake(s,row('c','記録','Push','ベンチプレス'),4);for(const [i,category] of ['身体状態','動作・効き','備考','メニュー変更'].entries())assert.equal(intake(s,row('n'+i,'補足','Pull','ダンベルカール','','分類='+category+'; 発言者='+ (i%2?'GPT':'本人'),'架空の本文'),5+i).status,'保存済み');assert.equal(s.tables.TrainingSessions.size,3);assert.equal(s.tables.TrainingNotes.size,4);assert.equal(s.tables.TrainingSets.get(a.record_id).rpe,null);assert.equal(s.tables.DailySummary.get('2026-10-02').training_set_count,3);});
test('explicit completion, plan binding, cancel and undo keep session and sets',()=>{const s=fresh(),op=cycleOp();app(s,op);const a=intake(s,row('set','記録','Push','ベンチプレス'),2),sid=ctx.hubP3SessionId_(s,'2026-10-02','Push');const c=row('complete','修正','Push','セッション','','状態=完了; CycleID='+op.entity_id+'; 予定枠='+op.entity_id+'#1');assert.equal(intake(s,c,3).status,'保存済み');assert.equal(s.tables.TrainingSessions.get(sid).lifecycle_state,'completed');assert.equal(s.tables.TrainingSessions.get(sid).ended_at,null);assert.equal(intake(s,c,4).status,'重複');assert.equal(intake(s,row('cancel','取消','Push','セッション','',''),5).status,'保存済み');assert.equal(s.tables.DailySummary.get('2026-10-02').training_set_count,0);assert.equal(intake(s,['undo','戻す','筋トレ','','','','','対象受付番号=cancel',''],6).status,'保存済み');assert.equal(s.tables.TrainingSessions.get(sid).lifecycle_state,'completed');assert.equal(s.tables.DailySummary.get('2026-10-02').training_set_count,1);assert.equal(s.tables.TrainingSets.get(a.record_id).session_id,sid);});
test('wrong plan kind, unknown cycle and reversed times become review without completion',()=>{const s=fresh(),op=cycleOp();app(s,op);intake(s,row('a','記録'),2);const sid=ctx.hubP3SessionId_(s,'2026-10-02','Pull');for(const [i,content] of ['状態=完了; CycleID='+op.entity_id+'; 予定枠='+op.entity_id+'#1','状態=完了; CycleID='+crypto.randomUUID(),'開始時刻=2026-10-02T11:00:00Z; 終了時刻=2026-10-02T10:00:00Z'].entries())assert.equal(intake(s,row('bad'+i,'修正','Pull','セッション','',content),3+i).status,'要確認');assert.equal(s.tables.TrainingSessions.get(sid).lifecycle_state,'in_progress');assert.equal(s.tables.Reviews.size,3);});
test('equipment and maximum attempt fields survive correction, cancel, undo and refresh',()=>{const s=fresh(),a=intake(s,row('a','記録','Push','ベンチプレス','1','重量kg=60; 回数=1; 機器=架空A; 変種=通常; 最大試技=はい; 成功=はい'),2);assert.equal(s.tables.TrainingSets.get(a.record_id).max_attempt,true);intake(s,row('edit','修正','Push','ベンチプレス','1','重量kg=65; 最大試技=いいえ'),3);assert.equal(s.tables.TrainingSets.get(a.record_id).equipment_key,'架空A');intake(s,['undo','戻す','筋トレ','','','','','対象受付番号=edit',''],4);assert.equal(s.tables.TrainingSets.get(a.record_id).weight_kg,60);assert.equal(s.tables.TrainingSets.get(a.record_id).max_attempt,true);});
test('additive migration preserves all old values including ledger and operations',()=>{const books=Object.fromEntries(Object.keys(baseline.tables).map(t=>[t,[]]));const old=copy({id:crypto.randomUUID(),revision:1,status:'active',created_at:'t',updated_at:'t',source_kind:'conversation',last_operation_id:crypto.randomUUID(),local_date:'2026-10-01',time_zone:'Asia/Tokyo',session:'Pull',cycle_id:null,started_at:null,ended_at:null});books.TrainingSessions=[old];const result=copy(ctx.hubP3MigrationPlan_(baseline,books));assert.equal(result.source_tables,16);assert.equal(result.target_tables,18);for(const key of Object.keys(old))assert.deepEqual(result.books.TrainingSessions[0][key],old[key]);assert.equal(result.books.TrainingSessions[0].lifecycle_state,null);assert.deepEqual(books.TrainingSessions,[old]);assert.deepEqual(result.books.Operations,books.Operations);books.TrainingSessions.push(copy(old));assert.throws(()=>ctx.hubP3MigrationPlan_(baseline,books),/MIGRATION_DUPLICATE_ID/);});

test('populated P2 books migrate with every field and opaque undo value unchanged',()=>{const h={exports:{}};new Function('require','module','__dirname',source+'\nmodule.exports={ctx,schema,fresh,intake,app,meal};')(require,h,__dirname);const legacy=h.exports,s=legacy.fresh(),op=legacy.meal();legacy.app(s,op);legacy.intake(s,row('old','記録'),2);legacy.intake(s,row('oldedit','修正','Pull','ダンベルカール','1','回数=10'),3);const books=Object.fromEntries(Object.entries(s.tables).map(([t,m])=>[t,[...m.values()]])),result=copy(ctx.hubP3MigrationPlan_(baseline,books));for(const [table,rows] of Object.entries(books))for(const [i,r] of rows.entries())for(const key of Object.keys(r))assert.deepEqual(result.books[table][i][key],r[key],table+'.'+key);assert.ok(result.books.UndoValues.length>0);assert.equal(result.books.Meals[0].id,op.entity_id);});
if(process.argv.includes('--schema'))fs.writeFileSync(__dirname+'/../Core/Sources/PHHHubCore/Resources/training-p3-schema.json',JSON.stringify(schema,null,2)+'\n');
test('app session revision, same operation and B2 response capability agree',()=>{const s=fresh();intake(s,row('a','記録'),2);const sid=ctx.hubP3SessionId_(s,'2026-10-02','Pull'),op={...meal(),action:'update_training_session',entity_id:sid,expected_revision:1,payload:{lifecycle_state:'completed',cycle_id:null,plan_slot_id:null}};const a=app(s,op);assert.equal(a.status,'committed');assert.deepEqual(a,app(s,op));assert.equal(s.tables.TrainingSessions.get(sid).revision,2);assert.equal(app(s,{...op,operation_id:crypto.randomUUID()}).error_code,'REVISION_CONFLICT');assert.equal(ctx.hubChanges_(s,{schema_version:1,environment:'PHH_TEST',synthetic:true,after:0,limit:500,generation:1}).training_contract,1);});


if(process.argv.includes('--fixture')) {
  const s=fresh(),op=cycleOp();app(s,op);
  intake(s,row('fixture1','記録','Push','ベンチプレス','1','重量kg=50; 回数=8; RPE=7'),2);
  intake(s,row('fixture2','記録','Push','ベンチプレス','2','重量kg=55; 回数=5'),3);
  intake(s,row('fixture-complete','修正','Push','セッション','','状態=完了; CycleID='+op.entity_id+'; 予定枠='+op.entity_id+'#1'),4);
  intake(s,row('fixture-note','補足','Push','ベンチプレス','','分類=身体状態; 発言者=本人','架空の補足'),5);
  const rows=['TrainingSessions','TrainingSets','TrainingNotes','TrainingCycles','TrainingPlanSlots'].flatMap(table=>[...s.tables[table].values()].map(values=>({table,values:Object.fromEntries(schema.tables[table].columns.map(c=>[c.name,values[c.name] ?? null]))})));
  fs.writeFileSync(process.argv[process.argv.indexOf('--fixture')+1],JSON.stringify({format:'phh-training-snapshot-v1',environment:'PHH_PRODUCTION',synthetic:true,source:'committed_canonical_snapshot',acquired_at:'2026-10-02T04:00:00Z',complete:true,rows},null,2));
}

vm.runInContext(fs.readFileSync(__dirname+'/Backup.gs','utf8'),ctx);
test('P3 backup checks full plan references and cancelled session counts',()=>{const s=fresh(),op=cycleOp();app(s,op);intake(s,row('backup-set','記録','Push','ベンチプレス'),2);intake(s,row('backup-bind','修正','Push','セッション','','状態=完了; CycleID='+op.entity_id+'; 予定枠='+op.entity_id+'#1'),3);intake(s,row('backup-cancel','取消','Push','セッション','',''),4);const tables=Object.fromEntries(Object.entries(s.tables).map(([t,m])=>[t,[...m.values()].map(r=>Object.fromEntries(schema.tables[t].columns.map(c=>[c.name,r[c.name] ?? null])))])),meta={schema_version:1,environment:'PHH_TEST',generation:1,snapshot_revision:ctx.hubSetting_(s,'next_change')};ctx.hubBackupValidate_(tables,meta);const broken=copy(tables);broken.TrainingPlanSlots.pop();assert.throws(()=>ctx.hubBackupValidate_(broken,meta));});


test('equipment-only edit and undo work without changing numeric values',()=>{const s=fresh(),a=intake(s,row('base','記録'),2);assert.equal(intake(s,row('equipment','修正','Pull','ダンベルカール','1','機器=架空B'),3).status,'保存済み');assert.equal(s.tables.TrainingSets.get(a.record_id).equipment_key,'架空B');intake(s,['undo-equipment','戻す','筋トレ','','','','','対象受付番号=equipment',''],4);assert.equal(s.tables.TrainingSets.get(a.record_id).equipment_key,null);assert.equal(s.tables.TrainingSets.get(a.record_id).weight_kg,10);});
assert.deepEqual(JSON.parse(fs.readFileSync(__dirname+'/../Core/Sources/PHHHubCore/Resources/training-p3-schema.json','utf8')),schema,'staged Swift and GAS schema equality');


test('published summary separates session state and keeps cancelled sets out',()=>{const s=fresh();intake(s,row('summary-set','記録'),2);intake(s,row('summary-cancel','取消','Pull','セッション','',''),3);const state=ctx.hubEmptyState_();ctx.hubLoadDate_(s,'2026-10-02',state);const text=ctx.intakeSummaryForHub_(state,'2026-10-02',now);assert.ok(text.includes('状態 cancelled'));assert.ok(!text.includes('undefined'));assert.ok(!text.includes('セット1'));});
console.log('Training P3: '+passed+' PASSED');
